# Generated by Django 4.2.7 on 2023-11-28 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=40, verbose_name='Описание')),
                ('status', models.CharField(max_length=50, verbose_name='Статус')),
                ('date_finish', models.DateField(auto_now_add=True, verbose_name='Время выполнения')),
            ],
        ),
    ]
