# Generated by Django 4.2.7 on 2023-11-28 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_alter_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='date_finish',
            field=models.DateField(blank=True, null=True, verbose_name='Время выполнения'),
        ),
    ]
