# Generated by Django 4.2.7 on 2023-11-29 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_task_date_finish'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='details_description',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
    ]
